<?xml version="1.0" encoding="UTF-8"?><testrun name="TestConexion" project="controlDeAccesos" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="controlDeAccesos.TestConexion" time="3.132" displayname="TestConexion" uniqueid="[engine:junit-jupiter]/[class:controlDeAccesos.TestConexion]">
    <testcase name="testConsultarReg" classname="controlDeAccesos.TestConexion" time="3.132" displayname="testConsultarReg()" uniqueid="[engine:junit-jupiter]/[class:controlDeAccesos.TestConexion]/[method:testConsultarReg()]">
      <failure>
        <expected>null</expected>
        <actual>controlDeAccesos.Registro@665df3c6</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;null&gt; but was: &lt;controlDeAccesos.Registro@665df3c6&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertNull.failNotNull(AssertNull.java:50)&#13;
	at org.junit.jupiter.api.AssertNull.assertNull(AssertNull.java:35)&#13;
	at org.junit.jupiter.api.AssertNull.assertNull(AssertNull.java:30)&#13;
	at org.junit.jupiter.api.Assertions.assertNull(Assertions.java:275)&#13;
	at controlDeAccesos.TestConexion.testConsultarReg(TestConexion.java:13)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
